-- MySQL Script generated by MySQL Workbench
-- Wed Feb  1 11:47:50 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bestiary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bestiary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bestiary` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bestiary` ;

-- -----------------------------------------------------
-- Table `bestiary`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestiary`.`author` (
  `id_author` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(95) NOT NULL,
  `biography` VARCHAR(555) NOT NULL,
  `portrait` VARCHAR(555) NOT NULL,
  PRIMARY KEY (`id_author`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


INSERT INTO `bestiary`.`author` (name, biography, portrait) VALUES 
(
  "H. P. Lovecraft",
  "Howard Phillips Lovecraft, né le 20 août 1890 à Providence (Rhode Island) et mort le 15 mars 1937 dans la même ville, est un écrivain américain connu pour ses récits fantastiques, d'horreur et de science-fiction (Weird Fiction). Ses sources d'inspiration, tout comme ses créations, se réfèrent à la notion d'horreur cosmique, selon laquelle l'être humain est insignifiant à l'échelle du cosmos qui lui est profondément étranger. Ceux qui raisonnent véritablement, comme ses protagonistes, mettent toujours en péril leur santé mentale.",
  "https://static.fnac-static.com/multimedia/Images/FD/Comete/123310/CCP_IMG_ORIGINAL/1606927.jpg"
),
(
  "H. R. Gieger",
  "Hans Ruedi Giger, plus connu en tant que HR Giger, (né à Coire, en Suisse, le 5 février 1940, et mort le 12 mai 2014 à Zurich, en Suisse) est un plasticien, graphiste, illustrateur, sculpteur et designer suisse.",
  "https://www.fribourgregion.ch/wp-content/uploads/2021/11/gruyere-23212-bf5220db4d9e94539751227154895ff8cbd7981b_3000.jpg"
);


-- -----------------------------------------------------
-- Table `bestiary`.`book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestiary`.`book` (
  `id_book` INT NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(155) NOT NULL,
  `genre` VARCHAR(90) NOT NULL,
  `fk_author_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_book`),
  INDEX `fk_author_id_idx` (`fk_author_id` ASC) VISIBLE,
  CONSTRAINT `fk_author_id`
    FOREIGN KEY (`fk_author_id`)
    REFERENCES `bestiary`.`author` (`id_author`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `bestiary`.`book` (book_name, genre, fk_author_id) VALUES
(
  "Le mythe de Cthulhu",
  "Fantastique - Horreur",
  1
),
(
  "La Quête Onirique de Kadath l'inconnue",
  "Fantastique - Horreur",
  1
),
(
  "Celui qui chuchotait dans le Noir",
  "Fantastique - Horreur",
  1
);
-- -----------------------------------------------------
-- Table `bestiary`.`creature`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestiary`.`creature` (
  `id_creature` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `description` VARCHAR(555) NULL DEFAULT NULL,
  PRIMARY KEY (`id_creature`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `bestiary`.`creature` (name, description) VALUES
(
  "Cthulhu",
  "Gigantesque créature extraterrestre endormie depuis des millénaires dans la cité de R'lyeh engloutie sous les flots de l'océan Pacifique, Cthulhu est vénéré tel un dieu par des humains dévoyés et des êtres aquatiques qui lui vouent un culte immémorial par le biais de sculptures antédiluviennes. Celles-ci reproduisent sa forme vaguement humanoïde complétée d'une tête de seiche, de tentacules de pieuvre et d'ailes semblables à celles d'un dragon."
),
(
  "Azathoth",
  "Azathoth, « le Sultan des Démons », est le maître des Autres Dieux (Other Gods) et existe depuis le commencement des temps. Il vit au centre de l'univers, au-delà de l'espace temps normal. Là, son corps informe se contorsionne sans cesse au son de la mélopée monotone d'une flûte, accompagné dans sa danse par les autres dieux qui l'entourent. Azathoth est décrit comme étant à la fois aveugle et stupide ; c'est un monstrueux chaos nucléaire."
),
(
  "Nyarlathotep",
  "Nyarlathotep, surnommé « le Chaos Rampant », est à la fois le messager, le cœur et l'âme des Autres Dieux (Other Gods). Dans le poème en prose Nyarlathotep, il est représenté comme un homme au teint bistre affirmant être sorti des ombres antiques des pyramides égyptiennes. Nyarlathotep voyage de ville en ville afin de dispenser un savoir impie qui dépasse l'être humain et conduit des villes entières à la folie, symbolisant ainsi l'horreur cosmique."
),
(
  "Alien",
  "Les Aliens (de l'anglais « étranger », et par extension « extraterrestre ») sont également désignés par le terme Xénomorphe, qui signifie « forme étrangère », et désigne plus généralement une créature non répertoriée. Les deux noms sont génériques, le cas particulier du cycle de reproduction suggérant en fait la cohabitation symbiotique de plusieurs espèces aux noms spécifiques variables."
);


-- -----------------------------------------------------
-- Table `bestiary`.`creature_in_book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestiary`.`creature_in_book` (
  `fk_creature_id` INT NULL DEFAULT NULL,
  `fk_book_id` INT NULL DEFAULT NULL,
  INDEX `fk_creature_id_idx` (`fk_creature_id` ASC) VISIBLE,
  INDEX `fk_book_id_idx` (`fk_book_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_id`
    FOREIGN KEY (`fk_book_id`)
    REFERENCES `bestiary`.`book` (`id_book`),
  CONSTRAINT `fk_creature_id`
    FOREIGN KEY (`fk_creature_id`)
    REFERENCES `bestiary`.`creature` (`id_creature`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `bestiary`.`creature_in_book` (fk_creature_id, fk_book_id) VALUES
(
  1, 1
),
(
  2, 2
),
(
  3, 3
);

-- -----------------------------------------------------
-- Table `bestiary`.`illustration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bestiary`.`illustration` (
  `id_illustration` INT NOT NULL AUTO_INCREMENT,
  `illustrator` VARCHAR(95) NOT NULL,
  `image` VARCHAR(555) NOT NULL,
  `fk_illustration_creature_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_illustration`),
  INDEX `fk_illustration_creature_id_idx` (`fk_illustration_creature_id` ASC) VISIBLE,
  CONSTRAINT `fk_illustration_creature_id`
    FOREIGN KEY (`fk_illustration_creature_id`)
    REFERENCES `bestiary`.`creature` (`id_creature`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

INSERT INTO `bestiary`.`illustration` (illustrator, image, fk_illustration_creature_id) VALUES 
(
  "Gou Tanabe",
  "https://img.20mn.fr/5ydAwjBsQpO52geo39DvoQ/768x492_bonjour-cthulhu-dis-veux-etre-ami",
  1
),
(
  "Loïc Muzy, Claire Delépée, Mariusz Gandzel",
  "https://www.bragelonne.fr/uploads/blog/2019/9-creatures-lovecraft/taille-reduite/azathoth.jpg",
  2
),
(
  "Loïc Muzy, Claire Delépée, Mariusz Gandzel",
  "https://www.bragelonne.fr/uploads/blog/2019/9-creatures-lovecraft/taille-reduite/nyarlathothep.jpg",
  3
),
(
  "H.  R. Gieger",
  "https://img.lemde.fr/2019/05/23/0/7/1046/523/1440/720/60/0/33a9048_2hAZCchers_gBj2CuFAbATi4.jpg",
  4
);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
